temp change, testing slack messages go out on failure...

diff --git a/.github/workflows/run_ingesters.yml b/.github/workflows/run_ingesters.yml
--- a/.github/workflows/run_ingesters.yml
+++ b/.github/workflows/run_ingesters.yml
@@ -15,6 +15,12 @@ jobs:
     steps:
       - name: Setup flyctl
         uses: superfly/flyctl-actions/setup-flyctl@master
+        
+      - name: (Test) Force failure
+        if: github.event_name == 'workflow_dispatch'
+        run: |
+          echo "Forcing a failure to test Slack notifications."
+          exit 1
 
       - name: Run ingesters (single-run, wait, cleanup)
         env:
@@ -89,7 +95,7 @@ jobs:
           flyctl machine destroy "$MACHINE_ID" -a "$APP" || true
 
           echo "Done."
-          
+
       - name: Notify Slack on workflow failure
         if: failure()
         env:
